name = "xinteria-labs"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Main entry point for the worker
main = ".vercel/output/static/_worker.js"

# Build configuration
[build]
command = "npm run cf:build"

[env.production]
name = "xinteria-labs-production"

[env.staging]  
name = "xinteria-labs-staging"

# Environment variables
[vars]
NODE_ENV = "production"

# Assets configuration for static files
[[assets]]
directory = ".vercel/output/static"
binding = "ASSETS"

# Uncomment and configure these sections as needed:

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "your-database-id"
